name: deploy-action-simple

on: [push] 

permissions:
  id-token: write
  contents: read
  pages: write

  
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20, 16]
        include:
          - os: windows-latest
            node: 20
            npm: 6
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies    
        run: npm ci
      - name: Build Project
        run: npm run build
        
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-${{ matrix.os }}-${{ matrix.version }}
          path: build/github-pages-${{ matrix.os }}-${{ matrix.version }}/
      
