name: using deploy action simple
 
on:
 workflow_call:
  inputs:
      versiones:
        required: true
        type: string
   
permissions:
  id-token: write
  contents: read
  pages: write



env:
  VERSIONS: "20"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  prepare-matrix:
    name: Prepare Matrix Output
    runs-on: ubuntu-latest
    outputs: 
      all_versions: ${{ steps.step1.outputs.matrix }}
    steps: 
      - name: Create Matrix Variable
        id: step1
        run: echo "matrix=${{env.VERSIONS}}" >> $GITHUB_OUTPUT


  salidas-datos:
     runs-on: ubuntu-latest
     steps:
      - name: Output Inputs 
        run: echo "${{ inputs.versiones }}"
      - name: Output matrix versiones 
        run: echo ${{ inputs.versiones }}
      - name: Output matrix.versiones uno
        run: echo "${{ matrix.node-version }}"
      - name: Output matrix.versiones dos 
        run: echo ${{ matrix.versiones }}
        
  build_test_release:
    needs: [prepare-matrix]
    strategy:
      matrix:
        node-version: ${{ fromJSON(needs.prepare-matrix.outputs.all_versions) }}
        os: ${{ fromJSON(github.ref == 'refs/heads/main' && '["ubuntu-latest"]' || '["ubuntu-latest", "windows-latest"]') }}
    runs-on: ${{ matrix.os }}
 
    steps:
      - name: Output Inputs 
        run: echo "${{ inputs.version_os }}"
      - name: Output matrix node version 
        run: echo ${{ inputs.version_os }}
      - name: Output matrix.node-version uno
        run: echo "${{ matrix.node-version }}"
      - name: Output matrix.node-version dos 
        run: echo ${{ matrix.node-version }}
        
      - uses: actions/checkout@v4
      - name: use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install

      - name: Build Project
        run: npm run build

     

        if: github.ref == 'refs/heads/main' && github.repository == 'REPO_OWNER/REPO_NAME'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: build 
          
      - name: Deploy with gh-pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: "github-pages"
