name: using deploy action simple
 
on:
 workflow_call:
  inputs:
      versiones:
        required: true
        type: string
   
permissions:
  id-token: write
  contents: read
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  prepare-matrix:
    name: Prepare Matrix Output
    runs-on: ubuntu-latest
    outputs: 
      all_versions: ${{ steps.step1.outputs.matrix }}
    steps: 
      - name: Create Matrix Variable
        id: step1
        run: echo "matrix=${{env.VERSIONS}}" >> $GITHUB_OUTPUT


  salidas-datos:
     runs-on: ubuntu-latest
     steps:
      - name: Output Inputs 
        run: echo "${{ inputs.versiones }}"
      - name: Output matrix versiones 
        run: echo ${{ inputs.versiones }}
      - name: Output matrix.versiones uno
        run: echo "${{ matrix.node-version }}"
      - name: Output matrix.versiones dos 
        run: echo ${{ matrix.versiones }}
        
  build_test_release:
    needs: [prepare-matrix]
    strategy:
      matrix:
        node-version: ${{ fromJSON(github.ref == 'refs/heads/main' && '[16]' || '[12,14,16]') }}
        os: ${{ fromJSON(github.ref == 'refs/heads/main' && '["ubuntu-latest"]' || '["ubuntu-latest", "windows-latest"]') }}
    runs-on: ${{ matrix.os }}
 
    steps:
      - name: Output Inputs 
        run: echo "${{ inputs.version_os }}"
      - name: Output matrix node version 
        run: echo ${{ inputs.version_os }}
      - name: Output matrix.node-version uno
        run: echo "${{ matrix.node-version }}"
      - name: Output matrix.node-version dos 
        run: echo ${{ matrix.node-version }}
       
